import { exec } from 'child_process'
import { promisify } from 'util'
import search from 'youtube-search-api'
import { unlinkSync, readFileSync, existsSync, readdirSync, mkdirSync, lstatSync, writeFileSync } from 'fs'
import path from 'path'

const execPromise = promisify(exec)

const ytCookies = `# Netscape HTTP Cookie File
# http://curl.haxx.se/rfc/cookie_spec.html
# This file was generated by Cookie-Editor
.youtube.com	TRUE	/	FALSE	1772806519	ST-3opvp5	session_logininfo=AFmmF2swRQIgGxZjllk0RG1xQlMHfDXfqPGlWKMUH3snaPkMxcKZfCUCIQDPQyNQ5RzH0oSYBBmz28hFet7PhGjfLslr-EHX8733Kw%3AQUQ3MjNmekp6el9YMTdvQVRNSG9wdHZBZGpTT2dsQkZMeEdSM1dyUTZ1OEQ4MmNpc0FFX3loQ3ZqSHo1eEI2bGdpNGtacmEzaDlMbks1bFlxSzZ5QUxSUC1vRU5scEhLN3phMGt3RnBWZ1dXRllrbG1nQWVWalNkcEdiR3FjWEJUSVdZbmRRSlgzTzJBRVdtNzR0aDgzdktLdDVyUXRzdUJudlNpSWpkUjlHS2dHSE14aGpkZFBlU29DVE5QSUpnampZTGRHci1oclBDbUlDUThUanhnSXQxLUVUb05xeWhKQQ%3D%3D
#HttpOnly_.youtube.com	TRUE	/	TRUE	1807366506	__Secure-3PSID	g.a0007gjH_0BBOWxNVFOxn0Avvw7UNGbmoXrubFFX-26PFq9ymUABLboGQXcktq36nCV0kmqKUAACgYKARcSARQSFQHGX2MirXwujO9SqEoyWq42adFMUhoVAUF8yKpNMSxIrFb7b-YWxdIpdQ4q0076
#HttpOnly_.youtube.com	TRUE	/	TRUE	1772807890	GPS	1
.youtube.com	TRUE	/	FALSE	1804342514	SIDCC	AKEyXzVModOTbw_YyaZXCfti5tS8JG8GSojCptRstjLm68BjQRIC9_hBxJ5N0to2SSw_Ns-2
.youtube.com	TRUE	/	FALSE	1807366506	SID	g.a0007gjH_0BBOWxNVFOxn0Avvw7UNGbmoXrubFFX-26PFq9ymUABEe2-AVOxSwakBe7xOLMCngACgYKAbQSARQSFQHGX2MiIRZj-Tj_aAisZToKUyNB7RoVAUF8yKqy2vfuOGdy3dXKSKc4m9mr0076
#HttpOnly_.youtube.com	TRUE	/	TRUE	1804342506	__Secure-1PSIDTS	sidts-CjUBBj1CYo6KFwORfkePKl1cVBtCCrtHcP4bENNIyUYr5Xz1_3KTsC57bGmyjqdxG_QDiACcbBAA
.youtube.com	TRUE	/	TRUE	1807366506	SAPISID	qF929LPTi3rLnaLL/Ag7KH0ZyvAAqFBD-W
#HttpOnly_.youtube.com	TRUE	/	TRUE	1804342514	__Secure-1PSIDCC	AKEyXzWg1uwVDzZVABz8qLH5AaG0bEOJnPBL4ww1VIRHsjDrAP8H3Oul7RI_ifVB6lm6_ASfKA
#HttpOnly_.youtube.com	TRUE	/	TRUE	1807366506	SSID	AvbvNzEXlQiUCFSF5
.youtube.com	TRUE	/	TRUE	1807366506	__Secure-1PAPISID	qF929LPTi3rLnaLL/Ag7KH0ZyvAAqFBD-W
#HttpOnly_.youtube.com	TRUE	/	TRUE	1807366506	__Secure-1PSID	g.a0007gjH_0BBOWxNVFOxn0Avvw7UNGbmoXrubFFX-26PFq9ymUABmH_sJXg7bN9LAesBQqPM9wACgYKAUYSARQSFQHGX2MioD2qCTuNBfvm3zzaN9X9GRoVAUF8yKoRcIgUUWrd9bvdFvU8S1qL0076
.youtube.com	TRUE	/	TRUE	1807366506	__Secure-3PAPISID	qF929LPTi3rLnaLL/Ag7KH0ZyvAAqFBD-W
#HttpOnly_.youtube.com	TRUE	/	TRUE	1804342514	__Secure-3PSIDCC	AKEyXzXmDM0UuefyZdkjlZNODuPV2Po6EYE3gCJ5xuoI3zg8sYmsqKQnnqmjpsnTFzLYc5DA
#HttpOnly_.youtube.com	TRUE	/	TRUE	1804342506	__Secure-3PSIDTS	sidts-CjUBBj1CYo6KFwORfkePKl1cVBtCCrtHcP4bENNIyUYr5Xz1_3KTsC57bGmyjqdxG_QDiACcbBAA
#HttpOnly_.youtube.com	TRUE	/	TRUE	1788358090	__Secure-BUCKET	CIIE
#HttpOnly_.youtube.com	TRUE	/	TRUE	1806934087	__Secure-YENID	13.YTE=HmQLtAUkQGZWctHOQLyY5jggH-vCejEldHAF7SAsnXvNZF559hDd7p1lSvOmSI3LKhxKViFk4yGAFCUsIytuqECO8auCnncnIBiNHHLidQ9ZC4v1cGBzYJTPyE9ai40GrJyc-vPxR2pB6mbNqIeJ0HU0Nd6YALFPpy3iNhARiypjM919kNsEOq5uqpzxqCx94-H2XRYeMbLk5sNPYK4OSaAcdltmfAaQEbaJGJHnB1ZQiVMu0pLKt28tv7XHt1h3Q2hco8ao-R0NT569VsCiqPXCzhKDFwjH1fNudL1fzSkgWn5rTAFip3qOnZArp5u5chH8viZz9zf_fjQWGRHK3w
.youtube.com	TRUE	/	FALSE	1807366506	APISID	NrLqzPrh5VecZwHi/AYpbpnGgTDT2fLM8J
#HttpOnly_.youtube.com	TRUE	/	FALSE	1807366506	HSID	AU96RQILIEU8vt_JB
#HttpOnly_.youtube.com	TRUE	/	TRUE	1807366506	LOGIN_INFO	AFmmF2swRQIgGxZjllk0RG1xQlMHfDXfqPGlWKMUH3snaPkMxcKZfCUCIQDPQyNQ5RzH0oSYBBmz28hFet7PhGjfLslr-EHX8733Kw:QUQ3MjNmekp6el9YMTdvQVRNSG9wdHZBZGpTT2dsQkZMeEdSM1dyUTZ1OEQ4MmNpc0FFX3loQ3ZqSHo1eEI2bGdpNGtacmEzaDlMbks1bFlxSzZ5QUxSUC1vRU5scEhLN3phMGt3RnBWZ1dXRllrbG1nQWVWalNkcEdiR3FjWEJUSVdZbmRRSlgzTzJBRVdtNzR0aDgzdktLdDVyUXRzdUJudlNpSWpkUjlHS2dHSE14aGpkZFBlU29DVE5QSUpnampZTGRHci1oclBDbUlDUThUanhnSXQxLUVUb05xeWhKQQ==
.youtube.com	TRUE	/	TRUE	1807366509	PREF	tz=Europe.Rome
.youtube.com	TRUE	/	TRUE	1806934090	SOCS	CAISEwgDEgk4Nzg5Njk4OTIaAml0IAEaBgiAsqjNBg
#HttpOnly_.youtube.com	TRUE	/	TRUE	1788358090	VISITOR_INFO1_LIVE	zwnq0Ge5Jr0`

let handler = async (m, { conn, command, args, usedPrefix }) => {
    const tmpDir = path.resolve('./tmp')
    if (!existsSync(tmpDir)) mkdirSync(tmpDir, { recursive: true })

    const cookiePath = path.resolve(tmpDir, 'yt_cookies.txt')
    if (!existsSync(cookiePath)) writeFileSync(cookiePath, ytCookies.trim(), 'utf-8')
    const cookieFlag = `--cookies "${cookiePath}"`

    if (command === 'play' && !args.length) {
        return m.reply(`🏮 Uso: \`${usedPrefix}play [titolo]\``)
    }

    if (args[0] === 'audio' || args[0] === 'video') {
        let isAudio = args[0] === 'audio'
        let url = args[1]
        if (!url || !url.includes('youtu')) return m.reply('🏮 Link non valido.')

        await m.reply(`⏳ Scaricando ${isAudio ? 'audio' : 'video'}...`)
        let baseName = `${Date.now()}`
        let cmd = [
            'yt-dlp',
            cookieFlag,
            '--js-runtime node',
            '--force-ipv4',
            '--no-warnings',
            '--no-check-certificate',
            isAudio ? '-f "ba/b" --extract-audio --audio-format mp3' : '-f "bv*[ext=mp4]+ba[ext=m4a]/best[ext=mp4]/b"',
            `-o "${tmpDir}/${baseName}.%(ext)s"`,
            `"${url}"`
        ].join(' ')

        try {
            await execPromise(cmd)
            let files = readdirSync(tmpDir)
            let found = files.find(f => f.startsWith(baseName) && !f.endsWith('.txt'))
            if (!found) throw new Error('File non generato')
            
            let finalPath = path.join(tmpDir, found)
            let data = readFileSync(finalPath)
            
            if (isAudio) {
                await conn.sendMessage(m.chat, { audio: data, mimetype: 'audio/mpeg', fileName: `audio.mp3` }, { quoted: m })
            } else {
                await conn.sendMessage(m.chat, { video: data, mimetype: 'video/mp4', caption: '> annoyed System' }, { quoted: m })
            }
            unlinkSync(finalPath)
        } catch (e) {
            console.error(e)
            m.reply(`❌ Errore durante il download.`)
        }
        return
    }

    let query = args.join(' ')
    let results = await search.GetListByKeyword(query, false, 1)
    if (!results || !results.items || results.items.length === 0) return m.reply('❌ Nessun risultato.')

    const v = results.items[0]
    const videoUrl = `https://www.youtube.com/watch?v=${v.id}`
    let thumb = v.thumbnail?.thumbnails?.[0]?.url || ''
    if (thumb.startsWith('//')) thumb = 'https:' + thumb

    let caption = `╭┈➤ 『 🎵 』 *YOUTUBE PLAY*\n┆  『 📌 』 \`titolo\` ─ ${v.title}\n╰┈➤ 『 📦 』 \`annoyed system\``

    const buttons = [
        { buttonId: `${usedPrefix}play audio ${videoUrl}`, buttonText: { displayText: '🎵 AUDIO' }, type: 1 },
        { buttonId: `${usedPrefix}play video ${videoUrl}`, buttonText: { displayText: '🎥 VIDEO' }, type: 1 }
    ]

    const buttonMessage = {
        image: { url: thumb },
        caption: caption,
        footer: 'Seleziona un formato',
        buttons: buttons,
        headerType: 4
    }

    return await conn.sendMessage(m.chat, buttonMessage, { quoted: m })
}

handler.command = ['play']
export default handler